name: Update IAM Policy

on:
  workflow_dispatch:
    inputs:
      user_email:
        description: 'User Email to grant access'
        required: true
      project_id:
        description: 'GCP Project ID'
        required: true

jobs:
  update-iam-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ github.event.inputs.project_id }}

      - name: Install yq (mikefarah version)
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          yq --version

      - name: Fetch current IAM policy
        run: gcloud projects get-iam-policy ${{ github.event.inputs.project_id }} > policy.yaml

      - name: Print Policy
        run: cat policy.yaml

      - name: Update policy.yaml
        run: |
          echo "Updating IAM policy with user: ${{ github.event.inputs.user_email }}"
          yq eval '.bindings += [{"role": "roles/viewer", "members": ["user:${{ github.event.inputs.user_email }}"]}]' -i policy.yaml

      - name: Apply updated IAM policy
        run: gcloud projects set-iam-policy ${{ github.event.inputs.project_id }} policy.yaml
