name: Smoke Tests Workflow

on:
  workflow_dispatch:
    inputs:
      smoke_tests:
        description: 'Run Smoke Tests? (yes or no)'
        required: true
        default: 'no'

jobs:
  run-smoke-tests:
    if: ${{ github.event.inputs.smoke_tests == 'yes' }}
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step to trigger the tests
      - name: Run Smoke Tests
        id: run_tests
        run: |
          echo "Running Smoke Tests..."
          # Simulating the test JSON output
          echo '{"Passed": "5", "Failed": "4", "Flaky": "1"}' > result.json

      # Step to process the JSON output
      - name: Process Test Results
        id: process_results
        run: |
          echo "Processing test results..."
          results=$(cat result.json)
          echo "Test results: $results"

          # Extract the Failed key value
          failed=$(echo $results | jq -r '.Failed' | xargs)
          if [ "$failed" -gt 0 ]; then
            echo "Test failed with $failed failed cases."
            exit 1
          fi
          echo "All tests passed successfully."

        # Install jq for JSON parsing
        shell: bash
        env:
          SMOKE_TEST_RESULTS: ${{ steps.run_tests.outputs.json_output }}

  skip-smoke-tests:
    if: ${{ github.event.inputs.smoke_tests != 'yes' }}
    runs-on: ubuntu-latest

    steps:
      - name: Skip Smoke Tests
        run: echo "Smoke tests not triggered as input was set to 'no'."
