name: Smoke Tests Workflow

on:
  workflow_dispatch:
    inputs:
      smoke_tests:
        description: 'Run Smoke Tests? (yes or no)'
        required: true
        default: 'no'

jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Conditional step: Check if smoke tests should be run
      - name: Check Input for Smoke Tests
        id: check_input
        run: |
          if [ "${{ github.event.inputs.smoke_tests }}" != "yes" ]; then
            echo "Smoke tests input is 'no', skipping the tests."
            exit 0
          fi
          echo "Proceeding with smoke tests."

      # Step to trigger smoke tests
      - name: Run Smoke Tests
        id: run_tests
        run: |
          echo "Running Smoke Tests..."
          # Simulate creating the JSON output
          echo '{"Passed": "5", "Failed": "4", "Flaky": "1"}' > result.json

      # Step to process the JSON output
      - name: Process Test Results
        id: process_results
        run: |
          echo "Processing test results..."
          results=$(cat result.json)
          echo "Test results: $results"

          # Extract values from the JSON
          passed=$(echo $results | jq -r '.Passed' | xargs)
          failed=$(echo $results | jq -r '.Failed' | xargs)
          flaky=$(echo $results | jq -r '.Flaky' | xargs)

          echo "Passed tests: $passed"
          echo "Failed tests: $failed"
          echo "Flaky tests: $flaky"

          # Fail the workflow if there are failed tests
          if [ "$failed" -gt 0 ]; then
            echo "Test failed with $failed failed cases."
            exit 1
          fi
          echo "All smoke tests passed successfully."

      # Install jq for JSON parsing
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
        if: ${{ github.event.inputs.smoke_tests == 'yes' }}
