name: Conditional Smoke Tests Workflow

on:
  workflow_dispatch:
    inputs:
      smoke_tests:
        description: 'Run Smoke Tests'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false

jobs:
  smoke-tests-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step to run smoke tests conditionally
      - name: Run Smoke Tests
        if: ${{ github.event.inputs.smoke_tests == 'true' }}
        id: run_smoke_tests
        run: |
          # Simulate running smoke tests and save the results to a JSON file
          echo '{
            "Passed": "5",
            "Failed": "4",
            "Flaky": "1"
          }' > smoke_test_results.json
          echo "Smoke tests completed."
          cat smoke_test_results.json

      # Step to parse results and fail if there are failures
      - name: Parse Smoke Test Results
        if: ${{ github.event.inputs.smoke_tests == 'true' }}
        run: |
          # Read and parse the JSON results
          results=$(cat smoke_test_results.json)
          failed_count=$(echo "$results" | jq -r '.Failed | tonumber')

          # Check if Failed count > 0
          if [ "$failed_count" -gt 0 ]; then
            echo "Smoke tests failed with $failed_count failures."
            exit 1
          else
            echo "All smoke tests passed successfully!"
          fi
