name: Workflow B - Generate Test Results

on:
  workflow_dispatch:

jobs:
  generate-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Test Results
        id: test_results
        run: |
          echo '{
            "Passed": "5",
            "Failed": "1",
            "Flaky": "1"
          }' > results.json

      - name: Output Results
        id: output_results
        run: |
          results=$(cat results.json)
          echo "::set-output name=results::$results"
