name: Workflow A - Trigger and Process Output

on:
  workflow_dispatch:  # Manually triggered

jobs:
  trigger_and_wait:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow B
        id: trigger_b
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/workflow-b.yml/dispatches \
            -d '{"ref": "master"}'

          echo "Triggered Workflow B"

      - name: Wait for Workflow B to Complete
        id: wait_b
        run: |
          sleep 30  # Wait to let Workflow B start

          # Fetch the latest run ID of Workflow B
          RUN_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?event=workflow_dispatch" | \
            jq -r '.workflow_runs[] | select(.name=="Workflow B - Generate Output") | .id' | head -n 1)

          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

          while true; do
            STATUS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID" | \
              jq -r '.status')

            if [[ "$STATUS" == "completed" ]]; then
              break
            fi
            echo "Waiting for Workflow B to complete..."
            sleep 15
          done

      - name: Fetch Output from Workflow B
        id: fetch_output
        run: |
          OUTPUT=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID" | \
            jq -r '.jobs[].steps[] | select(.name=="Generate Output").outputs.smoke_test_result')

          echo "Output from Workflow B: $OUTPUT"
          echo "::set-output name=smoke_test_result::$OUTPUT"
